// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

// user login info
export const USER_LOGIN_INFO = "USER_LOGIN_INFO";
export const TOKEN_INFO = "TOKEN_INFO";
export const REMEMBER_ME_INFO = "REMEMBER_ME_INFO";

//groups 
export const GROUP_LIST = "GROUP_LIST";
export const GET_LIST_GROUP_SELECTED_ROWS = "GET_LIST_GROUP_SELECTED_ROWS";

//Tour
export const TOUR_LIST = "TOUR_LIST";
export const TOUR_DETAIL = "TOUR_DETAIL";
export const GET_LIST_TOUR_SELECTED_ROWS = "GET_LIST_TOUR_SELECTED_ROWS"
export const IMAGE_LIST = "IMAGE_LIST";

//Order
export const TOUR_ORDER = "TOUR_ORDER";


//loading
export const OPEN_LOADING = "OPEN_LOADING";
export const CLOSE_LOADING = "CLOSE_LOADING";